package me.velz.facility.utils;

import lombok.Getter;

public enum MessageUtil {

    // Prefix Messages
    PREFIX("§3Facility &8┃ ", "§3Facility &8┃ "),
    
    // Error Messages
    ERROR_NOPERMISSIONS("§cDazu hast du keine Berechtigung.", "§cYou don't have permissions."),
    ERROR_PLAYERONLY("§cDieser Befehl kann nur von einem Spieler genutzt werden.", "§cThis command can only used by a player."),
    ERROR_PLAYERNOTFOUND("§cDieser Spieler konnte nicht gefunden werden.", "§cThis player cannot be found."),
    ERROR_NONUMBER("§cDu musst eine gültige Zahl angeben.", "§cYou must enter a valid number."),
    ERROR_NOITEMINHAND("§cDu hast kein Item in der Hand.", "§cYou dont have an item in hand."),
    ERROR_NOTENOUGHITEMS("§cDu hast nicht genügend Items.", "§cYou don't have enough items."),
    ERROR_DATE("§cDiese Aktion kann nur zu einem bestimmten Datum erfolgen.", "§cThis action can used only at a specific date."),
    ERROR_SYNTAX("§cSyntax Fehler, bitte nutze: %command", "§cSyntax Error, please use: %command"),
    
    // Server Messages
    SERVER_JOIN("§e%player hat das Spiel betreten.", "§e%player has joined the game."),
    SERVER_QUIT("§e%player hat das Spiel verlassen.", "§e%player has left the game."),
    SERVER_FULL("§cDer Server ist derzeit voll.\n§cVersuche es später noch einmal.", "§cThe server is full.\nPlease try again later."),
    SERVER_TABLIST_HEADER("\n§eFacility\n§7Macht deinen Server besser!\n", "\n§eFacility\n§7Makes your Server better!\n"),
    SERVER_TABLIST_FOOTER("\n§6Get it on §bhttps://facility.zaros.ch/\n", "\n§6Get it on §bhttps://facility.zaros.ch/\n"),
    
    // Player Messages
    PLAYER_BOAT("§6Wir wünschen eine schöne Fahrt.", "§6We wish you a nice trip."),
    PLAYER_HEAL_SELF("§6Du hast dich geheilt.", "§6You healed yourself."),
    PLAYER_HEAL_OTHER("§6Du hast §e%player §6geheilt.", "§6You healed §e%player§6."),
    PLAYER_FEED_SELF("§6Du hast deinen Hunger gestillt.", "§6You satisfied your hunger."),
    PLAYER_FEED_OTHER("§6Du hast §e%players §6Hunger gestillt.", "§6You have satisfied the hunger of §e%player."),
    PLAYER_OPENINV("§6Du hast das Inventar von §e%player §6geöffnet.", "§6You opened the inventory of §e%player§6."),
    PLAYER_CLEARINV_SELF("§6Du hast dein Inventar geleert.", "§6You cleared your inventory."),
    PLAYER_CLEARINV_OTHER("§6Du hast das Inventar von §e%player §6geleert.", "§6You have cleared the inventory of §e%player§6."),
    PLAYER_KILL_SELF("§6Du hast dich selbst getötet.", "§6You killed yourself."),
    PLAYER_KILL_OTHER("§6Du hast §e%player §6getötet.", "§6You killed §e%player%."),
    PLAYER_HAT("§6Du hast das Item nun auf deinem Kopf.", "§6You have the item now on your head."),
    PLAYER_FLY_SELF_ON("§6Du hast deinen Flugmodus aktiviert.", "§6You have enabled fly mode."),
    PLAYER_FLY_SELF_OFF("§6Du hast deinen Flugmodus deaktiviert.", "§6You have disabled fly mode."),
    PLAYER_FLY_OTHER_ON("§6Du hast §e%players §6Flugmodus aktiviert.", "§6You have enabled fly mode for §e%player."),
    PLAYER_FLY_OTHER_OFF("§6Du hast §e%players §6Flugmodus deaktiviert.", "§6You have disabled fly mode for §e%player."),
    PLAYER_ENDERCHEST_SELF("§6Du hast deine Enderchest geöffnet.", "§6You opened your enderchest."),
    PLAYER_ENDERCHEST_OTHER("§6Du hast die Enderchest von §e%player §6geöffnet.", "§6You opened the Enderchest of §e%player§6."),
    PLAYER_WORKBENCH("§6Du hast eine Workbench geöffnet.", "§6You have opened your workbench."),
    PLAYER_ENCHANTMENTTABLE("§6Du hast einen Zaubertisch geöffnet.", "§6You opened an enchantment table."),
    PLAYER_GAMEMODE_SELF_SURVIVAL("§6Du bist nun im §eSurvival§6 Modus.", "§6You are now in §esurvival§6 mode."),
    PLAYER_GAMEMODE_SELF_CREATIVE("§6Du bist nun im §eKreativ§6 Modus.", "§6You are now in §ecreative§6 mode."),
    PLAYER_GAMEMODE_SELF_SPECTATOR("§6Du bist nun im §eZuschauer§6 Modus.", "§6You are now in §espectator§6 mode."),
    PLAYER_GAMEMODE_SELF_ADVENTURE("§6Du bist nun im §eAdventure§6 Modus.", "§6You are now in §eadventure§6 mode."),
    PLAYER_GAMEMODE_OTHER_SURVIVAL("§6Der Spieler §e%player§6 ist nun im §eSurvival§6 Modus.", "§6The player §e%player §6is now in §esurvival§6 mode."),
    PLAYER_GAMEMODE_OTHER_CREATIVE("§6Der Spieler §e%player§6 ist im §eKreativ§6 Modus.", "§6The player §e%player§6 is now in §ecreative§6 mode."),
    PLAYER_GAMEMODE_OTHER_SPECTATOR("§6Der Spieler §e%player§6 ist im §eZuschauer§6 Modus.", "§6The player §e%player§6 is now in §espectator§6 mode."),
    PLAYER_GAMEMODE_OTHER_ADVENTURE("§6Der Spieler §e%player§6 ist im §eAdventure§6 Modus.", "§6The player §e%player§6 is now in §eadventure§6 mode."),
    PLAYER_SPEED_SELF_FLY("§6Du hast deine Fluggeschwindigkeit auf §e%speed§6 gesetzt.", "§6You have set your fly speed to %speed."),
    PLAYER_SPEED_OTHER_FLY("§6Du hast §e%players§6 Fluggeschwindigkeit auf §e%speed§6 gesetzt.", "§6You have set the fly speed from §e%player§6 to §e%speed§6."),
    PLAYER_SPEED_SELF_WALK("§6Du hast deine Laufgeschwindigkeit auf §e%speed§6 gesetzt.", "§6You have set your walk speed to §e%speed§6."),
    PLAYER_SPEED_OTHER_WALK("§6Du hast §e%players§6 Laufgeschwindigkeit auf §e%speed§6 gesetzt.", "§6You have set the walk speed from §e%player§6 to §e%speed§6."),
    PLAYER_VANISH_SELF_ON("§6Du hast Vanish aktiviert.", "§6You have activate vanish."),
    PLAYER_VANISH_SELF_OFF("§6Du hast Vanish deaktiviert.", "§6You have disabled vanish."),
    PLAYER_VANISH_OTHER_ON("§6Du hast Vanish für §e%player§6 aktiviert.", "§6You have enabled vanish for §e%player§6."),
    PLAYER_VANISH_OTHER_OFF("§6Du hast Vanish für §e%player§6 deaktiviert.", "§6You have disabled vanish for §e%player§6."),
    PLAYER_GODMODE_SELF_ON("§6Du hast den Godmodus aktiviert.", "§6You have enabled godmode."),
    PLAYER_GODMODE_SELF_OFF("§6Du hast den Godmodus deaktiviert.", "§6You have disabled godmode."),
    PLAYER_GODMODE_OTHER_ON("§6Du hast Godmodus für §e%player§6 aktiviert.", "§6You have enabled godmode for §e%player§6."),
    PLAYER_GODMODE_OTHER_OFF("§6Du hast Godmodus für §e%player§6 deaktiviert.", "§6You have disabled the godmode for §e%player§6."),
    PLAYER_PING_SELF("§6Du hast einen Ping von §e%pingms§6.", "§6You have a ping of §e%pingms§6."),
    PLAYER_PING_OTHER("§6Der Spieler §e%player §6hat einen Ping von §e%pingms§6.", "§6The player §e%player §6has a ping of §e%pingms§6."),
    PLAYER_FREEZE_ON("§6Du hast §e%player §6eingefroren.", "§6You froze §e%player§6."),
    PLAYER_FREEZE_OFF("§6Du hast §e%player §6aufgetaut.", "§6You defrosted §e%player§6."),
    PLAYER_ROCKET_SELF("§6Du hast dich in die Luft katapultiert.", "§6You have catapulted yourself into the air."),
    PLAYER_ROCKET_OTHER("§6Du hast §e%player§6 in die Luft katapultiert.", "§6You have catapulted §e%player §6into the air."),
    PLAYER_LEVEL_GET("§6Der Spieler §e%player §6hat ein Level von §e%level§6.", "§6The player §e%player §6is level §e%level§6."),
    PLAYER_LEVEL_ADD("§e%player§6 wurden §e%level§6 hinzugefügt.", "§6Added §e%level§6 levels to §e%player."),
    PLAYER_LEVEL_TAKE("§e%player§6 wurden §e%level§6 entnommen.", "§6Taken §e%level§6 level from §e%player."),
    PLAYER_LEVEL_SET("§6Du hast §e%player§6 auf §e%level§6 Level gesetzt.", "§6You have set §e%player's§6 level to §e%level§6."),
    PLAYER_SEEN_HEADER("§6Spieler Informationen von §e%player", "§6Player information from §e%player"),
    PLAYER_SEEN_MESSAGE("§6Spielzeit: §f%playtime\n§6Kontostand: §f%money\n§6Gruppe: §f%group\n§6Erster Server beitritt: §f%firstjoin\n§6Zuletzt gesehen: §f%lastjoin", "§6Playtime: §f%playtime\n§6Money: §f%money\n§6Group: §f%group\n§6First join: §f%firstjoin\n§6Last join: §f%lastjoin"),
    PLAYER_SUDO_COMMAND("§6Befehl wurde ausgeführt.", "§6Command was executed."),
    PLAYER_SUDO_CHAT("§6Nachricht wurde gesendet.", "§6Message was sent."),
    TELEPORT_TP_SELF("§6Teleportiere zu §e%player§6.", "§6Teleporting to §e%player§6."),
    TELEPORT_TP_OTHER("§6Teleportiere §e%player §6zu §e%target§6.", "§6Teleporting §e%player §6to §e%target§6."),
    TELEPORT_TPHERE("§6Teleportiere §e%player §6zu dir.", "§6Teleporting §e%player §6to you."),
    TELEPORT_TPLOC_SELF("§6Teleportiere dich zu §e%loc§6.", "§6Teleporting to §e%loc§6."),
    TELEPORT_TPLOC_OTHER("§6Teleportiere §e%player §6zu §e%loc§6.", "§6Teleporting §e%player §6to §e%loc§6."),
    TELEPORT_TPA_PLAYER("§6Du hast §e%player §6eine Teleportanfrage geschickt.", "§6You sent §e%player §6a teleport request."),
    TELEPORT_TPA_ALREADY("§cDiesem Spieler hast du bereits eine Teleportanfrage geschickt.", "§cYou already sent a teleport request to this player."),
    TELEPORT_TPA_NOREQUEST("§cDieser Spieler hat dir keine Teleportanfrage geschickt.", "§cThis player didn't send you an teleport request."),
    TELEPORT_TPA_CANCEL_PLAYER("§cDu hast deine Teleportanfrage zu §e%player §cabgebrochen.", "§cYou have cancelled your teleport request to §e%player§c."),
    TELEPORT_TPA_SAMEPLAYER("§cDu kannst dich nicht zu dir selbst teleportieren.", "§cYou can't teleport to yourself."),
    TELEPORT_TPA_CANCEL_TARGET("§e%player §chat seine Teleportanfrage zu dir abgebrochen.", "§e%player §chas cancelled his teleport request."),
    TELEPORT_TPA_TIMEOUT_PLAYER("§cDeine Anfrage zu §e%player §cist abgelaufen.", "§cYour teleport request to §e%player §cis expired."),
    TELEPORT_TPA_TIMEOUT_TARGET("§cDie Teleportanfrage von §e%player §cist abgelaufen.", "§cThe teleport request from §e%player §c is expired."),
    TELEPORT_TPA_TARGET("§e%player §6möchte §esich zu dir§6 teleportieren.", "§e%player §6asks for a teleport to you."),
    TELEPORT_TPA_TPAHERETARGET("§e%player §6möchte, dass §edu dich zu ihm§6 teleportierst.", "§e%player §6asks for teleport to him."),
    TELEPORT_TPA_ACCEPT("      §a[Annehmen]§r  ", "      §a[Accept]§r  "),
    TELEPORT_TPA_DENY("§c[Ablehnen]", "§c[Deny]"),
    TELEPORT_TPA_ACCPTED_PLAYER("§e%player §ahat deine Teleportanfrage angenommen.", "§e%player §ahad accept your teleport request."),
    TELEPORT_TPA_ACCPTED_TARGET("§aDu hast die Teleportanfrage von §e%player §aangenommen.", "§aYou have accept the teleport request from §e%player§6."),
    TELEPORT_TPA_DENIED_PLAYER("§e%player §chat deine Teleportanfrage abgelehnt.", "§e%player §chad denied your teleport request."),
    TELEPORT_TPA_DENIED_TARGET("§6Du hast die Teleportanfrage von §e%player §6abgelehnt.", "§6You have denied the teleport request from §e%player§6."),
    TELEPORT_TELEPORTCANCEL("§cDer Teleportationsvorgang wurde abgebrochen.", "§cTeleport cancelled. Please don't move."),
    TELEPORT_TELEPORTSTART("§6Du wirst in §e%seconds Sekunden§6 teleportiert, bitte bewege dich nicht.", "§6You will be teleported in §e%seconds seconds§6, please don't move."),
    TELEPORT_JUMP_TOOFAR("§cDas ist leider zu weit.", "§cThat's too far."),
    WARP_TELEPORT_SELF("§6Teleportiere zu §e%warp§6.", "§6Teleporting to §e%warp§6."),
    WARP_TELEPORT_OTHER("§6Teleportiere §e%player §6zu §e%warp §6.", "§6Teleporting §e%player §6to §e%warp§6."),
    WARPLIST_PAGENOTFOUND("§cDiese Warplist Seite konnte nicht gefunden werden.", "§cThis warplist page doesn't exist."),
    WARP_NOWARPS("§cEs wurden noch keine Warps gesetzt.", "§cNo warps set."),
    WARP_SET("§6Du hast den Warp §e%warp §6gesetzt.", "§6You have set the warp §e%warp§6."),
    WARP_DEL("§6Du hast den Warp §e%warp §6gelöscht.", "§6You have deleted the warp §e%warp§6."),
    WARP_FOUND("§cDieser Warp wurde schon gesetzt.", "§cThis warp was already set."),
    WARP_NOTFOUND("§cDieser Warp konnte nicht gefunden werden.", "§cThis warp doesn't exist."),
    HOME_TELEPORT("§6Teleportiere zu deinem Home §e%home§6.", "§6Teleporting to your home §e%home§6."),
    HOME_SET("§6Du hast den Home '§e%home§6' gesetzt.", "§6You have set your home §e%home§6."),
    HOME_DELETE("§6Du hast den Home '§e%home§6' gelöscht.", "§6You have deleted the home §e%home§6."),
    HOME_LIST("§6Deine Home-Punkte: §f%list", "§6Homes: §f%list"),
    HOME_NOTFOUND("§cDiesen Home hast du noch nicht gesetzt.", "§cA home with this name couldn't not found."),
    HOME_NOHOMES("§cDu hast noch keine Homes gesetzt.", "§cNo homes set."),
    ITEMS_MORE("§6Dein Item wurde vermehrt.", "§6Your item got increased."),
    ITEMS_SKULL("§6Du hast den Kopf von §e%skull §6erhalten.", "§6You got the head of §e%skull§6."),
    SPAWN_TELEPORT_SELF("§6Teleportiere zum Spawn.", "§6Teleport you to the spawn."),
    SPAWN_TELEPORT_OTHER("§6Du hast §e%player §6zum Spawn teleportiert.", "§6You have teleported §e%player §6to the spawn."),
    SPAWN_NOTSET("§cDer Spawn wurde noch nicht gesetzt.", "§cThe spawn was not set."),
    SPAWN_SET("§6Du hast den Spawn gesetzt.", "§6You have set the spawn."),
    CHAT_BROADCAST("§cRundruf §7┃ §c%message", "§cBroadcast §7┃ §c%message"),
    CHAT_TEAMCHAT("§cTeam §7┃ %player§f: %message", "§cTeam §7┃ %player§f: %message"),
    CHAT_MSG_SELF("§7[ §6Du §f➡ §6%player §7] §f%message", "§7[ §6You §f➡ §6%player §7] §f%message"),
    CHAT_MSG_TARGET("§7[ §6%player §f➡ §6Dir §7] §f%message", "§7[ §6%player §f➡ §6You §7] §f%message"),
    CHAT_MSG_TARGETSELF("§cDu kannst dir nicht selbst schreiben.", "§cYou can't write to yourself."),
    CHAT_MSG_NOTFOUND("§cDu hast noch mit niemanden geschrieben.", "§cYou haven't wrote with somebody."),
    CHAT_CLEAR("§6Der Chat wurde von §e%player §6bereinigt.", "§6The chat was cleaned by §e%player§6."),
    CHAT_GLOBALMUTE_ON("§6Der Chat wurde von §e%player §6deaktiviert.", "§6The chat was disabled by §e%player§6."),
    CHAT_GLOBALMUTE_OFF("§6Der Chat wurde von §e%player §6aktiviert.", "§6The chat was enabled by §e%player§6."),
    CHAT_GLOBALMUTE_CANCEL("§cDer Chat wurde deaktiviert.", "§cThe chat was disabled."),
    CHAT_SOCIALSPY_ON("§6Du hast Socialspy aktiviert.", "§6You have activated socialspy."),
    CHAT_SOCIALSPY_OFF("§6Du hast Socialspy deaktiviert.", "§6You have deactivated socialspy."),
    CHAT_SOCIALSPY_MSG("§cSPY-MSG §7┃ §6%player §f➡ §6%target§f: %message", "§cSPY-MSG §7┃ §6%player §f➡ §6%target§f: %message"),
    CHAT_MOTD("§cWillkommen!\nDieser Server benutzt Facility!", "§cWelcome!\nThis Server is using Facility!"),
    MISC_SPAWNMOB_UNKNOWNMOB("§cDu hast einen ungültigen EntityType angegeben.", "§cYou have entered a invalid entity type."),
    MISC_SPAWNMOB_OTHER("§6Du hast §e%amountx %type §6bei §e%player §6erschaffen.", "§6You have spawned §e%amount §6of §e%type§6 to §e%player§6."),
    MISC_SPAWNMOB_SPAWNED("§6Du hast §e%amountx %type§6 erschaffen.", "§6You have spawned §e%amount §6of §e%type§6."),
    MISC_WEATHER_RAIN("§6Du hast es regenen lassen.", "§6You let it rain."),
    MISC_WEATHER_SUN("§6Du hast den Regen weg geblasen.", "§6You blow the rain away."),
    MISC_TIME_DAY("§6Du hast die Zeit auf §eTag§6 gesetzt.", "§6You set the time to day."),
    MISC_TIME_NIGHT("§6Du hast die Zeit auf §eNacht§6 gesetzt.", "§6You set the time to night."),
    MISC_TIME_NUMBER("§6Du hast die Zeit auf §e%number§6 gesetzt.", "§6You set the time to %number."),
    MISC_BLOCKPHYSICS_ON("§6Du hast Block Physics §eaktiviert§6.", "§6You have activated block physics."),
    MISC_BLOCKPHYSICS_OFF("§6Du hast Block Physics §edeaktiviert§6.", "§6You have deactivated block physics."),
    MISC_SETSPAWNER_TARGET("§cBitte schaue einen Spawner an.", "§cPlease look on a spawner."),
    MISC_SETSPAWNER_CHANGED("§6Der Spawner spawnt nun §e%type§6.", "§6The spawner is spawning now §e%type§6."),
    MISC_SETSPAWNER_TYPE("§cBitte verwende einen gültigen EntityType.", "§cPlease use a valid entity type."),
    MONEY_PREFIX("§3Geld §7┃ ", "§3Money §7┃ "),
    MONEY_BALANCE_SELF("§6Du hast §e%money %moneyname§6.", "§6You have §e%money %moneyname§6."),
    MONEY_BALANCE_OTHER("§e%player §6hat §e%money %moneyname§6.", "§e%player §6has §e%money %moneyname§6."),
    MONEY_NOTENOUGH("§cDu hast nicht genug %moneyname.", "§cYou don't have enough %moneyname."),
    MONEY_PAY_PLAYER("§6Du hast §e%target§6 %money %moneyname gegeben.", "§6You have give §e%target §6%money %moneyname§6."),
    MONEY_PAY_TARGET("§e%player§6 hat dir §e%money %moneyname§6 gegeben.", "§e%player §6has sent you §e%money %moneyname."),
    MONEY_PAY_SELF("§cDu kannst dir selber kein Geld geben.", "§cYou can't send yourself money."),
    MONEY_BALANCETOP_HEADER("§6Die Reichsten Spieler:", "§6The richest players:"),
    MONEY_BALANCETOP_ENTRY("§a#%place  §7-  §6%player  §7-  §b%money", "§a#%place  §7-  §6%player  §7-  §b%money"),
    MONEY_HELP_CHECK("§6/%moneyname <Spieler> §f➡ Spieler Kontostand anschauen", "§6/%moneyname <player> §f➡ Show balance of player"),
    MONEY_HELP_PAY("§6/%moneyname pay <Spieler> <Betrag> §f➡ Betrag überweisen", "§6/%moneyname pay <player> <amount> §f➡ Transfer money to other player"),
    MONEY_HELP_SET("§6/%moneyname set <Spieler> <Betrag> §f➡ Kontostand setzen", "§6/%moneyname set <player> <amount> §f➡ Set the balance of a player"),
    MONEY_HELP_GIVE("§6/%moneyname give <Spieler> <Betrag> §f➡ Betrag überweisen", "§6/%moneyname give <player> <amount> §f➡ Give someone money"),
    MONEY_HELP_TAKE("§6/%moneyname take <Spieler> <Betrag> §f➡ Betrag abbuchen", "§6/%moneyname take <player> <amount> §f➡ Take someone money."),
    MONEY_HELP_GIVEALL("§6/%moneyname giveall <Betrag> §f➡ Jedem einen Betrag überweisen", "§6/%moneyname giveall <amount> §f➡ Give all money"),
    MONEY_HELP_TAKEALL("§6/%moneyname takeall <Betrag> §f➡ Jedem einen Betrag abbuchen", "§6/%moneyname takeall <amount> §f➡ Take all money"),
    MONEY_HELP_TOP("§6/%moneyname top §f➡ Topliste anzeigen", "§6/%moneyname top §f➡ Shows the toplist."),
    MONEY_SET("§e%players §6Kontostand wurde auf §a%money %moneyname §6gesetzt.", "§e%player's §6balance was set to §a%money %moneyname§6."),
    MONEY_GIVE("§e%player §6wurden §e%money %moneyname§6 gutgeschrieben.", "§e%player §6got added §e%money %moneyname§6."),
    MONEY_GIVEINFO("§aDu hast §e%money %moneyname §aerhalten.", "§aYou got §e%money %moneyname§a."),
    MONEY_TAKEINFO("§cDir wurden §e%money %moneyname §cabgezogen.", "§e%money %moneyname§c got removed from you."),
    MONEY_GIVEALL("§6Du hast jeden §f%money %moneyname §agegeben.", "§6You gave all players §e%money %moneyname§6."),
    MONEY_TAKEALL("§6Du hast jeden §f%money %moneyname §cabgezogen.", "§6You take from all players §e%money %moneyname§6."),
    MONEY_TAKE("§e%player §6wurden §e%money %moneyname§6 abgezogen.", "§6You take §e%money %moneyname §6from §e%player§6."),
    PLAYTIME_SELF("§6Du hast eine Spielzeit von §e%playtime§6.", "§6You have a playtime of §e%playtime§6."),
    PLAYTIME_OTHER("§e%player §6hat eine Spielzeit von §e%playtime§6.", "§e%player §6had a playtime of §e%playtime§6."),
    PLAYTIME_HOUR("Stunde", "hour"),
    PLAYTIME_HOURS("Stunden", "hours"),
    PLAYTIME_MINUTE("Minute", "minute"),
    PLAYTIME_MINUTES("Minuten", "minutes"),
    PLAYTIME_H("h", "h"),
    PLAYTIME_M("m", "m"),
    PUNISH_BYPASSPUNISH("§cDieser Spieler darf nicht bestraft werden.", "§cThis player can't be punished."),
    PUNISH_KICKSCREEN("§cDu wurdest vom Server gekickt.\n §cGrund: §e%reason", "§cYou got kicked from server.\n§cReason: §e%reason"),
    PUNISH_KICKED("§e%name §7wurde für §c%reason §7gekickt.", "§e%name §7was kicked for §c%reason§7."),
    PUNISH_KICKEDHOVER("§cPunisher: §e%punisher", "§cPunisher: §e%punisher"),
    PUNISH_KICK("§aDer Spieler wurde gekickt.", "§aThe player was kicked."),
    PUNISH_ALREADYBANNED("§cDieser Spieler ist bereits gebannt.", "§cThis player is already banned."),
    PUNISH_ALREADYMUTED("§cDieser Spieler ist bereits gemutet.", "§cThis player is already muted."),
    PUNISH_BANNEDBROADCAST("§e%name §7wurde für §c%reason §7gebannt.", "§c%name §7got banned for §c%reason§7."),
    PUNISH_MUTEDBROADCAST("§e%name §7wurde für §c%reason §7gemutet.", "§c%name §6got muted for §c%reason§7."),
    PUNISH_BAN("§aDer Spieler wurde gebannt.", "§cThe player got banned."),
    PUNISH_BANNEDSCREEN("§cDein Account wurde vom Server ausgeschlossen.\n §cDauer: §e%time \n §cGrund: §e%reason", "§cYour account has been banned from the server.\n §cDuration: §e%time \n §cReason: §e%reason"),
    PUNISH_BANNEDHOVER("§cPunisher: §e%punisher\n §cDauer: §b%time", "§cPunisher: §e%punisher\n §cDuration: §b%time"),
    PUNISH_MUTEDHOVER("§cPunisher: §e%punisher\n §cDauer: §b%time", "§cPunisher: §e%punisher\n §cDuration: §b%time"),
    PUNISH_UNBAN("§aDer Spieler wurde entbannt.", "§aThe player got unbanned."),
    PUNISH_UNMUTE("§aDer Spieler wurde entmutet.", "§aThe player got unmuted."),
    PUNISH_UNBANNED("§e%name §7wurde entbannt.", "§e%name §7got unbanned."),
    PUNISH_UNMUTED("§e%name §7wurde entmutet.", "§e%name §6got unmuted."),
    PUNISH_UNBANNEDHOVER("§cPunisher: §e%punisher", "§cPunisher: §e%punisher"),
    PUNISH_UNMUTEDHOVER("§cPunisher: §e%punisher", "§cPunisher: §e%punisher"),
    PUNISH_NOTBANNED("§cDieser Spieler ist nicht gebannt.", "§cThis player is not banned."),
    PUNISH_NOTMUTED("§cDieser Spieler ist nicht gemutet.", "§cThis player is not muted."),
    PUNISH_MUTED_MESSAGE("§r\n§cDu wurdest vom Chat ausgeschlossen.\n§cVerbleibende Zeit:§e %time\n§cGrund:§e %reason\n§r", "§r\n§cYou are muted.\n§cDuration:§e %time\n§cReason:§e %reason\n§r"),
    KIT_GIVEKIT("§6Du hast dir das Kit §e%kit §6gegeben.", "§6You have got the §e%kit§6 kit."),
    KIT_NOTFOUND("§cDieses Kit konnte nicht gefunden werden.", "§cThis kit can't be found."),
    KIT_LIST("§6Kits: §f%kits", "§6Kits: §f%kits"),
    KIT_NOKITS("§cKeine Kits gefunden.", "§cNo kits found."),
    KIT_CREATE("§6Du hast das Kit §e%kit §6erstellt.", "§6You created the §e%kit §6kit."),
    KIT_DELETE("§6Du hast das Kit §e%kit §6gelöscht.", "§6You deleted the §e%kit §6kit."),
    KIT_NOTREADY("§cDu kannst das Kit noch nicht erneut nutzen.", "§cYou can't use this kit yet again, please try later."),
    KIT_ALREADYEXIST("§cEs gibt bereits ein Kit mit diesem Namen.", "§cA kit with this name already exists."),
    TRASH_TITLE("Müll", "Trash"),
    TRASH_MESSAGE("§6Viel Spaß beim Müll entsorgen.", "§6Have fun by dispose of garbage."),
    FACILITY_HELP_RELOAD("§6/facility reload §f➡ Alle Konfigurationen neuladen", "§6/facility reload §f➡ Reload your configuration."),
    FACILITY_RELOAD("§6Alle Konfigurationen wurden neugeladen.", "§6Configuration reloaded."),
    
    FUNC_INVENTORY_HELP_OPEN("§6/inventory open <Inventory> [Player] §f➡ Inventar öffnen", "§6/inventory open <inventory> [player] §f➡ Open inventory"),
    FUNC_INVENTORY_HELP_ADD("§6/inventory additems <Inventory> §f➡ Items hinzufügen", "§6/inventory additems <inventory> §f➡ Add items to inventory"),
    FUNC_INVENTORY_HELP_MOVE("§6/inventory moveitems <Inventory> §f➡ Items verschieben", "§6/inventory moveitems <inventory> §f➡ Move items"),
    FUNC_INVENTORY_HELP_LIST("§6/inventory list §f➡ Alle Inventare anzeigen lassen", "§6/inventory list §f➡ Display all inventories"),
    
    FUNC_INVENTORY_ITEMSMOVE("§aEinfach die Items verschieben um die Position zu ändern.", "§aMove simply the items to your wished position."),
    FUNC_INVENTORY_ITEMSADD("§aEinfach die neuen Items ins Inventar packen.", "§aPut the new items in this inventory, to add."), 
    FUNC_INVENTORY_ITEMSMOVED("§aDie Positionen der Items wurden gespeichert.", "§aPositions are saved."),
    FUNC_INVENTORY_SLOTNOTFOUND("§cEs konnte kein freie Slot mehr gefunden werden.", "§cA free slot was not found."),
    FUNC_INVENTORY_ITEMSADDED("§aDie Items wurden dem Inventar hinzugefügt.", "§aThe items added to the inventory."),
    FUNC_INVENTORY_NOINVENTORIES("§cEs konnten keine Inventare gefunden werden.", "§cNo inventories found."),
    FUNC_INVENTORY_LIST("§6Inventare: §f%invs", "§6Inventories: §f%invs"),
    FUNC_INVENTORY_NOTFOUND("§cDieses Inventar konnte nicht gefunden werden.", "§cThis inventory couldn't found."),
    FUNC_INVENTORY_OPEN("§aInventar wurde geöffnet.", "§aInventory was opened.");

    @Getter
    private String local, english, german;

    private MessageUtil(String english, String local) {
        this.local = local;
        this.english = english;
    }
    
    public static String getMessage(MessageUtil message, String locale) {
        if(locale.equalsIgnoreCase("de")) {
            return message.getLocal();
        }
        return message.getEnglish();
    }

    public static void load() {
        FileBuilder message = new FileBuilder("plugins/Facility", "messages.yml");
        for (MessageUtil m : MessageUtil.values()) {
            message.addDefault("message." + m.toString().replaceAll("_", ".").toLowerCase(), m.local.replaceAll("§", "&"));
        }
        message.save();
        for (MessageUtil m : MessageUtil.values()) {
            m.local = message.getConfiguration().getString("message." + m.toString().replaceAll("_", ".").toLowerCase()).replaceAll("&", "§");
        }
    }

    public static void save(MessageUtil m) {
        FileBuilder message = new FileBuilder("plugins/Facility", "messages.yml");
        message.save();
    }

}
